# Generated by Django 3.1.2 on 2020-10-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('latitude', models.FloatField(max_length=30)),
                ('longitude', models.FloatField(max_length=30)),
                ('unique_squirrel_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('shift', models.CharField(default='AM', max_length=2)),
                ('date', models.DateField()),
                ('age', models.CharField(default='Adult', max_length=15)),
                ('primary_fur_color', models.CharField(default='Gray', max_length=15)),
                ('highlight_fur_color', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(default='Ground Plane', max_length=30)),
                ('specific_location', models.TextField(blank=True, max_length=128)),
                ('running', models.BooleanField(default=False)),
                ('chasing', models.BooleanField(default=False)),
                ('climbing', models.BooleanField(default=False)),
                ('eating', models.BooleanField(default=False)),
                ('foraging', models.BooleanField(default=False)),
                ('other_activity', models.TextField(blank=True, max_length=128)),
                ('kuks', models.BooleanField(default=False)),
                ('quaas', models.BooleanField(default=False)),
                ('moans', models.BooleanField(default=False)),
                ('tail_flags', models.BooleanField(default=False)),
                ('tail_twitches', models.BooleanField(default=False)),
                ('approaches', models.BooleanField(default=False)),
                ('indifferent', models.BooleanField(default=False)),
                ('runs_from', models.BooleanField(default=False)),
                ('other_interaction', models.TextField(blank=True, max_length=128)),
            ],
        ),
    ]
