# Generated by Django 3.1.2 on 2020-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='other_activity',
            new_name='other_activities',
        ),
        migrations.RenameField(
            model_name='sighting',
            old_name='other_interaction',
            new_name='other_interactions',
        ),
        migrations.AddField(
            model_name='sighting',
            name='above_ground_sighter_measurement',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sighting',
            name='color_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sighting',
            name='combination_of_primary_and_highlight_color',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sighting',
            name='hectare',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sighting',
            name='hectare_squirrel_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='lat_long',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
