# Generated by Django 3.1.2 on 2020-10-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201018_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(max_length=20),
        ),
    ]
